### ISSUE TITLE
build ppd file

### ISSUE THREAD

**Issue by TheCrimsonLady** [KaOS-Community-Packages/samsung-uld-printer#1]
Hi,

i am in the midst of setting up a CUPS server on a raspberry pi zero w for my Samsung C410W printer, but the CUPS server doesn't seem to have this particular printer available, but offers to upload a "ppd" file instead.

That's when i stubbled over your repository, but i don't really understand how i build a PPD file from your repository...

Could you help me out?

Cheers

**Comment by raul338** [comment]
the `PKGBUILD` is a shellscript that copies the ppd files from a zip downloaded from samsung official site (see the sources)

you can extract the file from that zip (should be in `noarch/share/ppd` directory)

AFAIK the zip should become with an installer, you can try that
